// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf8iQgGdlfoEEIg2wIptW-IeYpndcu-sA',
    appId: '1:297638072014:web:af4d4063d4a7df53d6ca9f',
    messagingSenderId: '297638072014',
    projectId: 'laundry-shoes-60205',
    authDomain: 'laundry-shoes-60205.firebaseapp.com',
    storageBucket: 'laundry-shoes-60205.firebasestorage.app',
    measurementId: 'G-16JT3H2DTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ZaResGfTqSYSL7g0_ufUxSwGoXNkiUU',
    appId: '1:297638072014:android:631e1ebc9f8bbbaed6ca9f',
    messagingSenderId: '297638072014',
    projectId: 'laundry-shoes-60205',
    storageBucket: 'laundry-shoes-60205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR5a42Xfb9h4QztPoOXLKlQOBeJtQK5rA',
    appId: '1:297638072014:ios:a7c49e4297437dacd6ca9f',
    messagingSenderId: '297638072014',
    projectId: 'laundry-shoes-60205',
    storageBucket: 'laundry-shoes-60205.firebasestorage.app',
    iosBundleId: 'com.laundrySepatu.laundrySepatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR5a42Xfb9h4QztPoOXLKlQOBeJtQK5rA',
    appId: '1:297638072014:ios:a7c49e4297437dacd6ca9f',
    messagingSenderId: '297638072014',
    projectId: 'laundry-shoes-60205',
    storageBucket: 'laundry-shoes-60205.firebasestorage.app',
    iosBundleId: 'com.laundrySepatu.laundrySepatu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf8iQgGdlfoEEIg2wIptW-IeYpndcu-sA',
    appId: '1:297638072014:web:875cbe691930dfb3d6ca9f',
    messagingSenderId: '297638072014',
    projectId: 'laundry-shoes-60205',
    authDomain: 'laundry-shoes-60205.firebaseapp.com',
    storageBucket: 'laundry-shoes-60205.firebasestorage.app',
    measurementId: 'G-VGB9FTY12F',
  );
}
